ktor:
  deployment:
    port: 8080

  application:
    modules:
      - kt.main.api.RoutingKt.restAPI

database:
  dbUrl: $dbUrl
  dbUser: $dbUser
  dbPassword: $dbPass

jwt:
  secret: $jwtSecret
  realm: $jwtRealm

webdav:
  token: $webdavToken