ktor:
  deployment:
    port: 8080

  application:
    modules:
      - kt.main.api.UserRestKt.userRestAPI
      - kt.main.api.MainRestKt.mainRestAPI

database:
  dbUrl: $dbUrl
  dbUser: $dbUser
  dbPassword: $dbPass

jwt:
  secret: $jwtSecret
  realm: $jwtRealm

webdav:
  token: $webdavToken